version: '3.8'

services:
  rezept-hopper:
    build: .
    container_name: rezept-hopper
    ports:
      - "8080:8080" # Container lauscht intern auf 8080 (siehe ENV ASPNETCORE_URLS)
    volumes:
      - rezept_hopper_data:/app/data # Sichert deine SQLite-Datenbank auf dem Host-Server
    restart: unless-stopped

volumes:
  rezept_hopper_data:
